meta:
  name_template: build-{{ .Instance }}
  instances:
  - a
  - b
  params:
    a:
    - name: param
      value: a
    b:
    - name: param
      value: b
data:
  {{ partial "job-def.yml" 0 . }}
